# Generated by Django 5.1.3 on 2024-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_mfa_enabled_account_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_confirmation_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
