# Generated by Django 5.1.4 on 2024-12-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
