# Generated by Django 5.1.4 on 2025-01-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_subscription_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
