# Generated by Django 5.1.4 on 2025-01-05 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_subscriptionitem_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pages.checkout', to_field='stripe_checkout_id'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pages.order')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pages.plan', to_field='stripe_plan_id')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pages.price', to_field='stripe_price_id')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pages.product', to_field='stripe_product_id')),
            ],
        ),
    ]
