# Generated by Django 5.1.4 on 2025-01-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='pages_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='pages_order_item',
        ),
    ]
