# Generated by Django 5.1.4 on 2025-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_observation_systemlog_apikey_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
