# Generated by Django 5.1.3 on 2024-12-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_id',
        ),
    ]
