curl --verbose --request POST http://127.0.0.1:8000/register \
--header "Content-Type: application/json" \
--data '{
  "username": "test-username",
  "name": "Test Name",
  "email": "testing@cleansmrs.com",
  "password": "123456@Aa"
}'

curl --verbose --request POST http://127.0.0.1:8000/login \
--header "Content-Type: application/json" \
--data '{
  "email": "testing@cleansmrs.com",
  "password": "123456@Aa"
}'

curl --verbose --request GET  http://127.0.0.1:8000/account \
--header "Content-Type: application/json" \
--header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhNTcxMWNiLWE2ZWItNDE5Zi04MWEwLTM3ZjVkNTU0ZjA3ZiIsImV4cCI6MTczMjg5MDMyMywiaWF0IjoxNzMyODg2NzIzfQ.oouN5hnwQJiOGShGBS0LCaSfttr4fk1NJGcgUZarJRY"

curl --verbose --request POST http://127.0.0.1:8000/logout \
--header "Content-Type: application/json" \
--header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhNTcxMWNiLWE2ZWItNDE5Zi04MWEwLTM3ZjVkNTU0ZjA3ZiIsImV4cCI6MTczMjg5MDMyMywiaWF0IjoxNzMyODg2NzIzfQ.oouN5hnwQJiOGShGBS0LCaSfttr4fk1NJGcgUZarJRY"
